apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobber-elastic-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage-elastic"
  hostPath:
    path: /data/elastic
    type: DirectoryOrCreate
