apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jobber-elastic
  namespace: development
spec:
  selector:
    matchLabels:
      app: jobber-elastic
  serviceName: jobber-elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: jobber-elastic
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command:
            ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.enrollment.enabled
              value: "false"
          ports:
            - name: elasticsearch
              containerPort: 9200
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            limits:
              cpu: "1500m"
              memory: "2Gi"
            requests:
              cpu: "800m"
              memory: "800Mi"
  volumeClaimTemplates:
    - metadata:
        name: elastic-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage-elastic"
        resources:
          requests:
            storage: 3Gi
