FROM node:alpine:3.20 as build
WORKDIR /app

COPY src ./src
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./

RUN touch package.json && \
    sed -i 's/"@Ronasunil/jobber-shared"/"@ronasunil/jobber-shared"/g' package.json
RUN npm install && npm i -g nodemon && npm i -g ts-node

EXPOSE 2002
CMD [ "npm", "run", "start:dev" ]

