services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server"]
    networks:
      - app-network
  mongodb:
    container_name: mongodb_container
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - app-network
  mysql:
    container_name: mysql_container
    image: mysql:8.4.4
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=jobber
      - MYSQL_DATABASE=jobber_app
      - MYSQL_USER=jobber
      - MYSQL_PASSWORD=jobber
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - app-network
    user: mysql

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
    networks:
      - elk-network
  # volumes:
  # - ./data/es:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.17.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_container:9200
    ports:
      - 5601:5601
    networks:
      - elk-network
    volumes:
      - ./kibana.yml/:/usr/share/kibana/config/kibana.yml:ro

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4.1-rc-management-alpine
    restart: always
    ports:
      # AMQP port
      - 5672:5672
      # DASHBOARD port
      - 15672:15672
    networks:
      - rabbitmq-network
    environment:
      - RABBITMQ_DEFAULT_USER=jobber-user
      - RABBITMQ_DEFAULT_PASS=jobber-pass
  notifications:
    container_name: notifications_container
    build:
      context: ./server/notification-service
      dockerfile: Dockerfile
    env_file: "./server/notification-service/src/config.env"
    restart: always
    environment:
      - APM_START="0"
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
      - NODE_ENV=development
      - PORT=2001
      - SENDER_EMAIL=gerson59@ethereal.email
      - SENDER_PASS=xpNGZcnBsaZhrP6Sku
      - SMTP_PORT=587
      - HOST=smtp.ethereal.email
      - APP_ICON=https://i.ibb.co/Kyp2m0t/cover.png
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - rabbitmq-network
      - elk-network
      - app-network
  gateway:
    container_name: gateway_container
    build:
      context: ./server/api-gateway-service
      dockerfile: Dockerfile
    env_file: ./server/api-gateway-service/src/config.env
    restart: always
    environment:
      - PORT=2000
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - NODE_ENV=development
      - COOKIE_SECRET=BPjGpCyg8BUxVCanXJazuGp8JRw2PGHC
      - CLIENT_URL=http://localhost:5173
      - API_GATEWAY_HEADER=secret-*-*&^*%$%%!^^^^-secret
      - JWT_SECRET=pzfHGlWkWDDvComxj8M9J6cfCn2tlIjB
      - AUTH_SERVICE_URL=http://auth_container:2002
      - USER_SERVICE_URL=http://user_container:2003
      - GIG_SERVICE_URL=http://gig_container:2004
      - CHAT_SERVICE_URL=http://chat_container:2005
      - APP_NOTIFICATION_SERVICE_URL=http://app_notification_container:2006
      - APP_NOTIFICATION_WS_URL=ws://app_notification_container:2006
      - ORDER_SERVICE_URL=http://order_container:2007
      - CHAT_WS_URL=ws://chat_container:2005
      - REVIEW_SERVICE_URL=http://review_container:2008
      - REDIS_HOST=redis://redis_container:6379
    depends_on:
      - redis
      - elasticsearch
      - chat
      - app-notification
    networks:
      - app-network
      - elk-network
      - rabbitmq-network

  app-notification:
    container_name: app_notification_container
    build:
      context: ./server/app-notification-service
      dockerfile: Dockerfile
    env_file: ./server/app-notification-service/src/config.env
    restart: always
    environment:
      - PORT=2006
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - API_GATEWAY_ENDPOINT=http://gateway_container:2000
      - MONGO_DB_ENDPOINT=mongodb://mongodb_container:27017/jobber
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
      - REDIS_ENDPOINT=redis://redis_container:6379
    networks:
      - app-network
      - elk-network
      - rabbitmq-network
    depends_on:
      - redis
      - elasticsearch
      - mongodb
      - rabbitmq

  auth:
    container_name: auth_container
    build:
      context: ./server/auth-service/
      dockerfile: Dockerfile
    env_file: ./server/auth-service/src/config.env
    restart: always
    environment:
      - PORT=2002
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - API_GATEWAY_ENDPOINT=http://gateway_container:2000
      - MYSQL_DB=mysql://root:jobber@mysql_container:3306/jobber_app
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
      - DEFAULT_PROFILE_IMG=https://res.cloudinary.com/dkljhbdej/image/upload/v1724154330/66c481d64ffb0c8a47a7fd99.png
      - JWT_SECRET=pzfHGlWkWDDvComxj8M9J6cfCn2tlIjB
      - APP_ICON=data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAMAAzAMBEQACEQEDEQH/xAAcAAEBAAIDAQEAAAAAAAAAAAAAAQQHAgUGAwj/xABDEAABAwMBBQUFAg0BCQAAAAABAAIDBAURBgcSITFBE1FhcYEUIjKRoVKyFRYjMzZDYnKSscHR8EIkJURkdIKis8L/xAAbAQEBAAMBAQEAAAAAAAAAAAAAAQMEBQYCB//EADYRAAICAgADBQYEBQUBAAAAAAABAgMEEQUhMRITQVFxIjJhgaHBFDOx4TRykdHwIyRCUmLx/9oADAMBAAIRAxEAPwDyi/RjlhCBCBAyhGQIQqAKECEKhAgCEKhAgAQjKh8hAEIVAEIVCBCFQBCBCBAzHVOiEIEDKjPkIgVAFGQIQqECAIQqECABCMqHyEAQhUAQhUIEIEBUIEIUIGEIYyp0QgKhAiIUIQKMBCFQgQBCFQgQBCMqHyEAQFQgQhUIEIEBUIEIVAwh8hAYyp0iofIQFQgUYCEKhGEAQhUIOmUA9R800Rs5BrjyaT6KbRCcufDzVIOSEKgCEKEIEIEBUIEIVCBCBAEIY6p0QmgVAFCBCFQjCECAqEHLmgPcaZ2dVlwaypuznUdO7iIgPyjx4/Z/muJmcZhU3Cn2n5+BtVYkp859DYds0pZLaxop7fCXgfnJW77j81wbs/Ju96T0b0KYQ91HcNY1gDWNa1o6NGAtOUnLqZUkY9XbqKsbu1dJBMDz7SMFfcbrIe7Jo+XFPqeVvezm1VjHPtpNDN03feYfMf2XVx+M31vVntL6mrZhwn7vJmsb5ZK+xVfs9wi3c57OQHLZAOeCvSY2VXkx7Vb/AGObZXKt6kdeFsmJhCBAVCBCFQgQgQFQgQGMro6JUAUIEIVCMIQICoQdFCG09nejo6eKO8XSLeqXe9BE8fmh0cR9r+S8xxXiTm3TU+Xi/P4HRx8dL2pHv5Zo4InyzPbHGwZc5xwAPFcOMXJqMVzNxvS2zwl82mUlM90VopzVuBx2r3brPTqV2sfgdliTtl2fh4mlbmqL1DmeZk2kahe7LfYmDo0Qk/zcumuCYiXPb+f7Gu8234GZb9p10jkAr6Onnj6mHMbh8yQfosVvAqX+XJr15n1HNmnzR73T2qbZf2YpJS2cDLoH8Hgf1HkuDlYN2K/bXLz8DeqyK7fdM+62ykvFC+jr4RJC/oebT0IPQjvWCi+yixWVvTMk4RmuyzR+prFPp+5upJiXRu96GXHB7f7r22Hlxyqu3Hr4o4V9TqlpnU9FtmIqECE2VCBCBAVCBAEIY6p0QpsBCFQmwhAgKhAgPR6Asrb1qKNkzd6nph20o6HB4D1P0C53FMl4+O3Hq+S+5mx6+3Yt9DeJwB0Ax8l4s65prXuqpb3WvoqSQtt0LsANP5532j4dwXruF8PjjwU5L239PQ5OTkOyTiuh5u3UFXc6kU9BTvmlI+Fg5DvPcF0rb66Ydqx6RrwjKb1FbPW0+zK8yRB8tRRwuP8Aoc5ziPkFypcdx09JNmysKbW29HV3rRd5s8ZmmgbNA0ZMkJ3gPMc1s43FMe99lPT8mYrMayHNrkdDTzz0s0dRTSOimjO8yRjuIPn/AIFv2QjOLhJbXkzXUpR5xZu3ROpG6htu9KGtrICGzNHf0cPA/wB14viOC8S3S919DtY1/ex+KOGv7KLzYJjG3NVTAyw45nHNvqP6K8Myfw+QvJ8n9iZVXeVvzRpIcQD3r2pw9lQmyoQIQICoQIAhCoQxk2dIIQqE2EIEBUIEAQhtjY/RCOzVlaR79RUbod3tYMD6ly8tx6xu6MPBL6v9tHQwY+y5eZ3O0K4vtmlKt8Ti2abEEZHMFxwT8srT4XSrsuKfRc/6GbKm4VvRpFjHPcyOJuXOcGMaOpPABe0k0ltnG1vkjfOlbBT2C1x08bQaggGeXq9/X07l4XNy55Vrk+ngvgdympVx0up2c9XTwFonmijJ4NDnAZ+a1owlJeytmRyiurPpweM8CCPQqdCmoNpWno7PcoqujYG0tYT7g5MkHMeo4+hXreD5jvrdc3zj+hx8ylVy7S8TD2e3B1u1VSN3iIqrMEg6HPw/+WPmVm4rQrcR+cef9/oY8SbhcvibtIXi+Z3D8+X2jFvvdfRtbushqHNYO5uct+hC9/jWd7RCfml+55y2PYscTCWcxhCBAVCBAEIVCBCGMh0ioQIQICoQIQICofJufZaB+J9Pg/rpc/xleO4z/GS9F+h1sP8AKMLa+Hfi/R4zu+2Nz/A/Cz8B1+Il/L90fGd7i9TXGmTGNSWky43PbIs5/fGPrhehzN/hrNf9X+hzqtd5Hfmj9AleCZ3jR20GGtGq6w3Bjy1zv9nLmkt7Phjd/wA55XtOFTq/CR7p9OvqcTLU+9e1y8DZmziOuj0tTNuQeJMuMbZPiEefdz9V53izqeVLuvn6nSxFNVLtHW7XiwacpQfjNY3c/gflbPAl/uJfy/dGLiGu6XqazsIcb7bOz+I1cO7j98L0mTpUWb/6v9Dl187Ir4o/QnReAPRGjNeY/HG6Y5dq37jV7fhv8HX/AJ4s4OX+fL/PA6Fb5qhAVCBAEIVCBCBAY6HRCECAqECEKgYQgQhtXY/WiS1V1AXe/BOJAP2Xj+7XLy/HqmrY2ea181+x0sGW4OJ32vrY+66WrIYW700YE0YHMlpzj1GR6rR4ZeqcqLl0fL+v7mbKrdlTS6mjWOILXsdgggtcOncfmvbNb5HGT8TemjtRQagtzH7zRVxtAqIuoPfjuK8Nn4csW1x/4vodrHuVsPid+6KN+N9jXY5ZGcLTTa6GZpPqcgAEKdJqnTdJqOCKKrdKx0W8Y3xu+EnHMcitvEzbMSTcPHqYbqI3LUjx9k0BW2vVFHUyzRTUMDjLvjg7IB3QR54Poutk8YhdjShFak+XwNKvClC1NvaRskkAZJwF53T6I6Z+e7zWi43iurGnLJp3uYf2c+79ML3+NV3VMK/JL9/qebtn25uXmYazmMqECAIQqECECAqEMZDohAVCBCAIGVCBCBCHoND3n8B6ghnkdinmHYzfunkfQ4+q5/Ecb8TjuK6rmv8APiZ8azu7Nvozeo3XtBGC0jIPevFa0do1LrXRNVT3IVNmp3S01VJjsmfqnuP0aT8l6nh/FISqcLnpx+q/ucnJxZKW4dGe+0jp6DT1tbAzDqiT3p5cfE7uHgFws7MnlWuT6eBv0UqqOvE75aZnCAICYHcgPK7Rb0LVY5IYn7tVVgxR45gH4nfJdLhWL396k/djzZqZl3d16XVml/IYHRezOEVCBCBCFQBCBAVCBCGOh0ghAhCoGEPkIAhCoBhCGytnesmlsdnu0mHDhTTuPBw+w49/cevnz83xXhjTd9K9V9zo4mTz7E/kbL4Lzx0SoAgCAIDrb7eKOyUL6uuk3WgYawfE89wHes+PjWZFihAx22wqj2pGj7/eam+3F9bV+7vDdZG05EbegH9SvaYuLDGrUIf/AE8/bdKyXaZ162jEEIEIVAEIAgKhAoQIRmOqdIIQqBhD5CAICoQIQoQgwhD12nNfXG0NZT1jTW0jeG6TiRg8HdfI/NcjM4RVfuUPZf0NurNnXylzRsC1a50/cGgmtbSv6x1X5Mj1PA+hXBu4VlVP3dr4czoV5dU/HXqd/HXUcrd6Kqge3vbICtOVU4vTizOpxfRmJXX60ULc1VypY/B0oz8uZX3DEvs5Rg38j5lbXFe0zyN72mUULXR2WnfVSdJpBuRj0PE/TzXVx+BWS53PS8lzf9jSs4hFcoLZrq63StvFUam4zmZ/IDkGjuA6L0WPj1Y8ezWtHMsulY9yMNZzEEIEIVAEIEBUIEIAhGVAYyHRKgCHyEBUIEAQhQhAhCoQIBhCcidm04y1vyV2/Ahd1o6D0Cmyci+iAqECECEKgCECAqECECEZUIEBjodLYQ+QgKhAgCEZR3IQIQIQqA5Nje4ZZG9w72tJ/kvlyS6sabXJEwckEEEHByqns+WtBUHJrHvzuMc7HPdaSo2l1ZObJgg4cCD3EYKJ76ECpNhCFQBCBAVCBCBQhVSBQBCGOqdEICoQIAhCjhlCPobf09p+zS6Mo6mW00D53UQe6V1MwuLt3nnHNeQysrIhmSgrHrtdNs69VUHQm14GoMc1684xe/wUA5YQht3ZSM6bef8AmHrynHP4leiOxga7o1hfM/h258se2Tf+xy9LjfkV/wAq/RHKv5WS9TC5LMYjY2x8e9dvKH/7XnuP9K/n9jp8N/5HndoQxq6t/wCz7oXQ4Tp4kfmaud+ezznVdLmahQhB1QgQhRx5IAoTYVBUPkIAhCoDGQ6JUIEACEKAhGwoyPoby01+glD/ANAPurxeb/Hz/m+53KfyF6GutEaOOoHPq6x74qCN277nB0rhzAPQeK7/ABLiX4X/AE4c5P6HNxsXvfal0PdPs2i6F7aKentrJjwDZngvPqTlcNZPEbV3kXLXw6G+6saHstI6PVez6nbSSV1gBa9g3nUxcXNe3ruHoVvYHGLO2q8jo/H+5r5GDHs9ur+h2eyj9GX8P+Ietbjv8Tr4GXh/5J9naY0xbqmepuxglmqpnyE1TxjLnE4DeXXCxrOzbYqFW0opLl8D7ePRGTlPqz4XzQNouFK6aztZS1G7mMxH8m/wI5D0WTG4xkVT7Nr7S8d9THbg1zW4cmddskikgqb1DM3dkjMTXNPDBBflbPHZKcapR6Pf2MXDouLkmeguOm7ALnU3e9OjkdMRgTv3WMAGOAzg+q59Wbld2qad8vI2rMertOyzR8LhovT13pN63sipnEe5PSkY9RyK+6eKZePPU3v4Mx2YVFsdx5ehrWDTVwmv5se61tQ13vvPFrW/b8sL0k86qOP+IXR9PXyOTHGm7u6ZsP8AFzSOnaeP8K9g+R3DtKt2S894byXnlncQy5bp38v7nV/D41C9vWz53DRlhvlAaqwujhkI/JyQOzG49xHIemF9VcUysazsZG2vHfU+bMOm6Par6/Q6DZ7p+hudVdILvSiV9L2bQ1ziN05cDyPguhxbMtqjXOiWk9mpgY0JymrF0PS0ug7JS1FTU1rBJG557GJ0hDIm9Bz4nzXMs4vkzjGEHrz82bkcCmLcpfI1VWNaysnZGMMErw0eGeC9XU24JvyOFZyk0vM+S+z4CEKgACEMdU6IQBCF5ITZ2Frslzu7ZH22ikqGxnD91zRun1K17sqmhpWy1s+4VTs91bMeuo6i31T6WtidDOzAcxxBIz5LJXZG2Hag9pnxOMo7jLqbq03+gtD0/wB3j7q8bmP/AH83/wCvudun8iPocdMt9j0LRPpgN4UXagftEbx+pKZn+pnSU/PXy6Eo9nHWvI0lNK+okfNOS+SQ7z3O5kle1jFQSivA4Lbk9y6m4tmNVPVaYaKhzndjM6NjndWj/MLyHGa4wyvZ8Vs7WDKUqVsyNDxMhp7nFDjcbcJgB3ceSx8Sk5Sg317KMmMlFPXmzVGp6uau1DcJaolzmVEkbQf9LWuIAHoF6rDqjVjwUfJP6HFvk52PtHu9kdTPJR11K9xdDC9pjychpOcgfJcLj1cY2Rn4s6HDZScWvA7uwRMi1lqZsYADvZnEDvLCT9ePqtLJlJ4dDf8A6/VGxUv9ezXw/Q1/tJqpqjVE8MxPZ07WtjYeQGM59V3+DVxhiqS6vqcziE3K5p9DsNk9XOy91FE0k08lO6Qt6BzXNAI/iK1+O1Q7mNninr9TJw2bVjj4GwY6WBupKioAHbOpGNcfDeK4Epy/Cxh4bf6HUUUre146Ok1Np6w3W7OqLneHwVAYG9l27G7g6cCPFb2HmZNNXZqr2vPTNbIxqbZ7nLn8j76bp9P6fjqI6O9RyMlcHOEtSw4I7sYWLMnlZTUp1ta+DPrHhTQmoz2viz5aUfA/VupX0r2PieYHhzHAgkh2fqvvNUlh0KX/AK+x84zi77Ozz6HjtplbUT6ilpHyu9nhY0MjB4ZIyThdjg1MI46mlzZzuJWSd3Z8DyS65zwhCoAEIVUhjIdIIQuEIEIex2Z32C03WalrZBHBWBoEjjhrXjlnuzyz4BcbjGJO+pTgtuJuYVqhPsvxPeX/AEZbL7WtrKh00U2A15idjfA71wsXid2NDu49DftxK7ZdqXU5anuNFpvTbqeMtYew7ClhzxPDA+QTDpsyslSfntsl1kaKtI6LZpqOCW2MslbI1tRESIN/9aw5OPMceHct7jGHONryILk+vwZgwr4uHdy5aPtXbM7fU1j54Kuenie7eMTQCB5Er5q43dCHZlFPXifU8CDltM7W43C2aLsLYIcBzWkU8APvSO7z4Z5ladNF3EcjtP5vwRlssrxq+z9PEw9l8r57BPNKcySVUj3HvJOStjjUVG9Rj0SSPjAe6tvzZ87lo6z6mnF1oax8ftHvOfBhzXnv48ilHE8jDj3M49PM+bMOu99uLO3oqS06Lskh7Tchb70kkh96R3QefQBatll/ELly2/0M8YV4tfwOg2cXCS53fUFdIMOnkidg9B7wA+QC3+L1Kimmvy39tmtg2d5Oc346Ozv2mLTqmofUMqjHVQuMUj4SCcjo4Fa2Jn34Uez2dp8+Zlvxash73zRkWKwWzSVJPOJubczVMxA4DkPAcViycu7Pmo69Ej6porxot/VnkqPW8X45y1cpc22zMFOHEfCAeDseZOfBdezhUvwKgvfXP9jQjnLv+0/d6HotUaOpNSysr6eqEUzmAdo1oeyRvQrn4XE54a7uS2v6M28jChkNST5mNRaNsFht0tReezqscXSzDAbjo0L7s4nl5NijRy+C+5814dFEG58/UxdmU0E9yvstHA2Cnc6IxxN5NHv4WbjUZxrqjN7fPn59DFw+SlOySWly+55baHx1bWHwb91dXhL/ANpE0eIfns84uiaJUACEKhAhDGVOkXCECEKEIEBm012udJF2VLcayGMDAZHO4NHkM8Fhnj0ze5QTfoiqycVqLZjSyyzyulqJZJZXcC+R5c4+pWSMIwWopJfA+W3J7bOBAPNfR8nZRagvUUXZR3etawch2xOPU8VrPDxpPbrW/QyK+1LSkzBlllnldLPLJLI74nyOLnHzJWeMYxWorSMbbb2z6wV1bTMLKatqoWE5LYp3sBPkCvmdVc3uUU/VIqnKK0mc6G519uLjQVk9PvcXCN5AJ8RyUsoqt9+KZIW2Q916OFZXVlfIJK6qmqHjkZXl275d3orXTXUtVxS9CTsnN7k9kp6uqpd72SqqIN74uxlczPngpOqufvRT9VsRsnD3Xo509fW01S+pp6yoinf8cjZSHP8AM9fVSVFU4qMopr0JG2cHuL0c6253C4Y9urZ6gNOQJJCQD345ZUrx6avcikJ2zs957MQcFlPgzKG63G3t3aGuqIGfZZIQ35clhsx6bec4p/I+oXWV+69HCtr6y4PDq6qmqCOI7V5cB5Dp6L6rprqWoRS9D5nbOx+09nGmq6qk3vZKqeDe+LsZXMz54Ks64T9+KfqtkjOUPdejjNLLPIZJ5ZJXnm+RxcT6lfUYRitRWj5cm+bOCpAEIVCBCBAY6p0QhCoQIAhGUIQIQIQqAIQIQqAIQIQqAKECpCoQKAqpAoQDmgKhAhChAEIYyp0SoQIQIGUIQIQIQqAIQIQqAIQIQqAKEYCEKqQKAqpAoQICqkChCoAhAhDHVOiEAQhUIEIEBUIEIEIVAEIEIVAFCMBCFVIFAFSFUIEBVSBQhUAQgQ+WEBjqnSCEKhAhAhCoAhAhCoAhAhCoAhAoQqpAoQKgqgGEIVUgUIVAEIEPllQgQH//2Q==
      - CLIENT_URL=http://localhost:5173
    networks:
      - app-network
      - elk-network
      - rabbitmq-network
    depends_on:
      - elasticsearch
      - mysql
      - rabbitmq
  chat:
    container_name: chat_container
    build:
      context: ./server/chat-service
      dockerfile: Dockerfile
    env_file: ./server/chat-service/src/config.env
    restart: always
    environment:
      - PORT=2005
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - API_GATEWAY_ENDPOINT=http://gateway_container:2000
      - MONGO_DB_ENDPOINT=mongodb://mongodb_container:27017/jobber
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
      - REDIS_ENDPOINT=redis://redis_container:6379
    networks:
      - app-network
      - elk-network
      - rabbitmq-network
    depends_on:
      - redis
      - elasticsearch
      - mongodb
      - rabbitmq
  gig:
    container_name: gig_container
    build:
      context: ./server/gig-service/
      dockerfile: Dockerfile
    env_file: ./server/gig-service/src/config.env
    restart: always
    environment:
      - PORT=2004
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - API_GATEWAY_ENDPOINT=http://gateway_container:2000
      - MONGO_DB_ENDPOINT=mongodb://mongodb_container:27017/jobber
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
      - REDIS_ENDPOINT=redis://redis_container:6379
    networks:
      - app-network
      - elk-network
      - rabbitmq-network
    depends_on:
      - redis
      - elasticsearch
      - mongodb
      - rabbitmq
  order:
    container_name: order_container
    build:
      context: ./server/order-service
      dockerfile: Dockerfile
    env_file: ./server/order-service/src/config.env
    restart: always
    environment:
      - PORT=2007
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - API_GATEWAY_ENDPOINT=http://gateway_container:2000
      - MONGO_DB_ENDPOINT=mongodb://mongodb_container:27017/jobber_user
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
      - REDIS_ENDPOINT=redis://redis_container:6379
      - STRIPE_API_KEY=sk_test_51QjmbQBnMJnUAXn31NpazJp3bJwFbTRAaivrOQE6BEvEkjSf8ik0Fh2XE2eJt6rjvFqXenziqyaQaDCxttffd51f00tbzFnRxi
    networks:
      - app-network
      - elk-network
      - rabbitmq-network
    depends_on:
      - redis
      - elasticsearch
      - mongodb
      - rabbitmq
  review:
    container_name: review_container
    build:
      context: ./server/review-service
      dockerfile: Dockerfile
    env_file: ./server/review-service/src/config.env
    restart: always
    environment:
      - PORT=2008
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - API_GATEWAY_ENDPOINT=http://gateway_container:2000
      - MYSQL_DB_ENDPOINT=mysql://root:jobber@mysql_container:3306/jobber_app
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
    networks:
      - app-network
      - elk-network
      - rabbitmq-network
    depends_on:
      - elasticsearch
      - mysql
      - rabbitmq
  user:
    container_name: user_container
    build:
      context: ./server/user-service
      dockerfile: Dockerfile
    env_file: ./server/user-service/src/config.env
    restart: always
    environment:
      - PORT=2003
      - ELASTIC_SEARCH_ENDPOINT=http://elasticsearch_container:9200
      - API_GATEWAY_ENDPOINT=http://gateway_container:2000
      - MONGO_DB_ENDPOINT=mongodb://mongodb_container:27017/jobber
      - RABBITMQ_ENDPOINT=amqp://jobber-user:jobber-pass@rabbitmq_container:5672
    networks:
      - app-network
      - elk-network
      - rabbitmq-network
    depends_on:
      - elasticsearch
      - mongodb
      - rabbitmq

  heartbeat:
    container_name: heartbeat
    image: docker.elastic.co/beats/heartbeat:8.17.1
    user: heartbeat
    restart: always
    cap_add:
      - NET_RAW
    command:
      - "--strict.perms=false"
      - "-e"
      - "-E"
      - 'output.elasticsearch.hosts=["http://elasticsearch_container:9200"]'
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    networks:
      - app-network
      - elk-network

  metricbeat:
    container_name: metricbeat_container
    image: docker.elastic.co/beats/metricbeat:8.17.1
    user: root
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command: metricbeat -e -E output.elasticsearch.hosts=["http://elasticsearch_container:9200"]
    networks:
      - app-network
      - elk-network
      - rabbitmq-network

  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:lts
    restart: always
    user: root
    privileged: true
    ports:
      - "5050:8080"
    volumes:
      - ./data/jenkins/jenkins_config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent:
    container_name: jenkins_agent_container
    image: ronasunil/jenkins_agent
    restart: always
    user: root
    privileged: true
    expose:
      - 22
networks:
  elk-network:
    driver: bridge
  rabbitmq-network:
    driver: bridge
  app-network:
    driver: bridge
