apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-user
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-user
  template:
    metadata:
      labels:
        app: jobber-user
    spec:
      containers:
        - name: myapp
          image: ronasunil/jobber-user:latest
          env:
            - name: PORT
              value: "2003"
            - name: ELASTIC_SEARCH_ENDPOINT
              value: "http://jobber-elastic.development.svc.cluster.local:9200"
            - name: API_GATEWAY_ENDPOINT
              value: "http://jobber-gateway.development.svc.cluster.local:2000"
            - name: MONGO_DB_ENDPOINT
              value: "mongodb://jobber-mongodb.development.svc.cluster.local:27017/jobber"
            - name: RABBITMQ_ENDPOINT
              value: "amqp://jobber-user:jobber-pass@jobber-rabbitmq.development.svc.cluster.local:5672"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "450m"
              memory: "650Mi"

          ports:
            - name: user
              containerPort: 2003
