apiVersion: v1
kind: Service
metadata:
  name: jobber-notify
  namespace: development
spec:
  selector:
    app: jobber-notify
  ports:
    - name: jobber-notify
      port: 2006
      targetPort: 2006
