apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-order
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-order
  template:
    metadata:
      labels:
        app: jobber-order
    spec:
      containers:
        - name: order
          image: ronasunil/jobber-order:latest
          env:
            - name: PORT
              value: "2007"
            - name: ELASTIC_SEARCH_ENDPOINT
              value: "http://jobber-elastic.development.svc.cluster.local:9200"
            - name: API_GATEWAY_ENDPOINT
              value: "http://jobber-gateway.development.svc.cluster.local:2000"
            - name: MONGO_DB_ENDPOINT
              value: "mongodb://jobber-mongodb.development.svc.cluster.local:27017/jobber"
            - name: RABBITMQ_ENDPOINT
              value: "amqp://jobber-user:jobber-pass@jobber-rabbitmq.development.svc.cluster.local:5672"
            - name: REDIS_ENDPOINT
              value: "redis://jobber-redis.development.svc.cluster.local:6379"
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jobber-secret
                  key: stripe_api_key
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "400m"
              memory: "600Mi"

          ports:
            - name: order
              containerPort: 2007
