apiVersion: v1
kind: Service
metadata:
  name: jobber-notification
  namespace: development
spec:
  selector:
    app: jobber-notification
  ports:
    - name: notification
      port: 2001
      targetPort: 2001
