apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobber-rabbitmq-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage-rabbitmq"
  hostPath:
    path: "/data/rabbitmq"
    type: DirectoryOrCreate
