apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-gig
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-gig
  template:
    metadata:
      labels:
        app: jobber-gig
    spec:
      containers:
        - name: gig
          image: ronasunil/jobber-gig:latest
          env:
            - name: PORT
              value: "2004"
            - name: ELASTIC_SEARCH_ENDPOINT
              value: "http://jobber-elastic.development.svc.cluster.local:9200"
            - name: API_GATEWAY_ENDPOINT
              value: "http://jobber-gateway.development.svc.cluster.local:2000"
            - name: MONGO_DB_ENDPOINT
              value: "mongodb://jobber-mongodb.development.svc.cluster.local:27017/jobber"
            - name: RABBITMQ_ENDPOINT
              value: "amqp://jobber-user:jobber-pass@jobber-rabbitmq.development.svc.cluster.local:5672"
            - name: REDIS_ENDPOINT
              value: "redis://jobber-redis.development.svc.cluster.local:6379"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "400m"
              memory: "700Mi"
          ports:
            - name: gig
              containerPort: 2004
