apiVersion: v1
kind: Service
metadata:
  name: jobber-mongodb
  namespace: development
spec:
  selector:
    app: jobber-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
