apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobber-redis-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage-redis"
  hostPath:
    path: "/data/redis"
    type: DirectoryOrCreate
