apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-kibana
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-kibana
  template:
    metadata:
      labels:
        app: jobber-kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.17.1
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://jobber-elastic.development.svc.cluster.local:9200"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - name: kibana
              containerPort: 5601
