apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobber-kibana
spec:
  ingressClassName: nginx
  rules:
    - host: kibana.jobber.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jobber-kibana
                port:
                  number: 5601
