apiVersion: v1
kind: Service
metadata:
  name: jobber-kibana
  namespace: development
spec:
  type: NodePort
  selector:
    app: jobber-kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30001
