apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobber-mysql-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage-mysql"
  hostPath:
    path: /data/mysql
    type: DirectoryOrCreate
